### ISSUE TITLE
Featured image uses wrong ALT tag on archive pages

### ISSUE THREAD

**Issue by viktorix** [KTS915/Bedrock#2]
On all archive pages, featured images use post title as an ALT tag even though they have an ALT tag set. Everything works as expected on a single post page.

**Comment by KTS915** [comment]
This is a feature inherited from Susty, and is designed to make sure that alt tags are given a value (because, as you know, they are often overlooked). You can change it by going to `inc/template-tags.php` and changing this:
```
the_post_thumbnail( 'post-thumbnail', array(
	'alt' => the_title_attribute( array(
		'echo' => false,
	) ),
) );
```
to simply this:
```
the_post_thumbnail();
```

**Comment by viktorix** [comment]
Thanks. It probably would be a good idea to perform a check, if the ALT tag is set or not.

**Comment by KTS915** [comment]
Agreed.

I also took the opportunity (since it works on the same filter) to add proper `loading` attributes (i.e. not the ham-fisted approach of giving every image a `loading` attribute of `lazy`).
